### ISSUE TITLE
Strange socket error :/

### ISSUE THREAD

**Issue by vkynchev** [vagabondan/CoiniumServ#11]
After merging the SEGWIT code this happened 3 times in a row... After the error the program stops.
Here is debug.log... Hmm... Couldn't replicate it...
```
08/18/2017 01:04:25 +03:00 [Information] [CoiniumServ.Utils.Platform.PlatformManager] [global] Running over .Net, framework: 4.5 (v4.0.30319.42000).
08/18/2017 01:04:27 +03:00 [Debug] [CoiniumServ.Pools.Pool] [Litecoin] Generated cryptographically random instance Id: 2896752899
08/18/2017 01:04:27 +03:00 [Debug] [Metrics.Metric] [global] Metrics: GlobalContext Name set to DESKTOP-5ORSFPL.CoiniumServ
08/18/2017 01:04:27 +03:00 [Debug] [CoiniumServ.Markets.MarketManager] [global] Recached market data - took 0.578 seconds
08/18/2017 01:04:28 +03:00 [Information] [CoiniumServ.Persistance.Providers.MySql.MySqlProvider] [Litecoin] Mysql storage initialized: 192.168.1.11:3306, database: litecoind.
08/18/2017 01:04:28 +03:00 [Information] [CoiniumServ.Persistance.Providers.Redis.RedisProvider] [Litecoin] Redis storage initialized: 192.168.1.11:6379, v{2:l}.
08/18/2017 01:04:29 +03:00 [Information] [CoiniumServ.Banning.BanManager] [Litecoin] No expired bans found to be cleared [remaining bans: 0].
08/18/2017 01:04:29 +03:00 [Information] [CoiniumServ.Jobs.Manager.JobManager] [Litecoin] Broadcasted new job 0x1 to 0 subscribers as no new blocks found for last 55 seconds
08/18/2017 01:04:29 +03:00 [Information] [CoiniumServ.Pools.NetworkInfo] [Litecoin] symbol: LTC algorithm: scrypt version: 140200 protocol: 70015 wallet: 130000 network difficulty: 0.00024414 block difficulty: 16.00 network hashrate: 35.90 MH/s network: testnet peers: 14 blocks: 153871 errors: none 
08/18/2017 01:04:29 +03:00 [Information] [CoiniumServ.Server.Mining.Stratum.StratumServer] [Litecoin] Stratum server listening on 0.0.0.0:2136
08/18/2017 01:04:29 +03:00 [Debug] [CoiniumServ.Pools.Pool] [Scorecoin] Generated cryptographically random instance Id: 452370437
08/18/2017 01:04:30 +03:00 [Information] [CoiniumServ.Persistance.Providers.MySql.MySqlProvider] [Scorecoin] Mysql storage initialized: 192.168.1.11:3306, database: scorecoind.
08/18/2017 01:04:30 +03:00 [Information] [CoiniumServ.Persistance.Providers.Redis.RedisProvider] [Scorecoin] Redis storage initialized: 192.168.1.11:6379, v{2:l}.
08/18/2017 01:04:30 +03:00 [Information] [CoiniumServ.Banning.BanManager] [Scorecoin] No expired bans found to be cleared [remaining bans: 0].
08/18/2017 01:04:30 +03:00 [Information] [CoiniumServ.Jobs.Manager.JobManager] [Scorecoin] Broadcasted new job 0x1 to 0 subscribers as no new blocks found for last 55 seconds
08/18/2017 01:04:30 +03:00 [Information] [CoiniumServ.Pools.NetworkInfo] [Scorecoin] symbol: SCORE algorithm: scrypt version: 1100000 protocol: 70006 wallet: 60000 network difficulty: 149.90269749 block difficulty: 9824023.18 network hashrate: 3.12 GH/s network: mainnet peers: 8 blocks: 116020 errors: none 
08/18/2017 01:04:30 +03:00 [Information] [CoiniumServ.Server.Mining.Stratum.StratumServer] [Scorecoin] Stratum server listening on 0.0.0.0:3621
08/18/2017 01:04:32 +03:00 [Debug] [CoiniumServ.Statistics.StatisticsManager] [global] Recached statistics - took 1.139 seconds
08/18/2017 01:04:34 +03:00 [Information] [CoiniumServ.Server.Web.WebServer] [global] Web-server listening on: http://localhost:8080/
08/18/2017 01:05:02 +03:00 [Debug] [CoiniumServ.Statistics.StatisticsManager] [global] Recached statistics - took 0.438 seconds
08/18/2017 01:05:05 +03:00 [Debug] [CoiniumServ.Server.Mining.Stratum.StratumServer] [Scorecoin] Stratum client connected: "192.168.1.15:34430"
08/18/2017 01:05:05 +03:00 [Debug] [CoiniumServ.Server.Mining.Stratum.StratumServer] [Litecoin] Stratum client connected: "192.168.1.15:59643"
08/18/2017 01:05:05 +03:00 [Debug] [CoiniumServ.Mining.MinerManager] [Litecoin] Authenticated miner: n3znnvqx498hUBgXcX9PX33MEs9yPMAsXa.a2terminator.15 [192.168.1.15:59643]
08/18/2017 01:05:05 +03:00 [Debug] [CoiniumServ.Mining.MinerManager] [Scorecoin] Authenticated miner: SbfEqa5BnqhjdS5K2whv5RN1ZMQhKZ9xsP.a2terminator1 [192.168.1.15:34430]
08/18/2017 01:05:05 +03:00 [Debug] [CoiniumServ.Server.Mining.Stratum.StratumServer] [Litecoin] Stratum client connected: "192.168.1.16:43036"
08/18/2017 01:05:05 +03:00 [Debug] [CoiniumServ.Server.Mining.Stratum.StratumServer] [Scorecoin] Stratum client connected: "192.168.1.16:60696"
08/18/2017 01:05:05 +03:00 [Debug] [CoiniumServ.Mining.MinerManager] [Litecoin] Authenticated miner: n3znnvqx498hUBgXcX9PX33MEs9yPMAsXa.a2terminator.16 [192.168.1.16:43036]
08/18/2017 01:05:05 +03:00 [Debug] [CoiniumServ.Mining.MinerManager] [Scorecoin] Authenticated miner: SbfEqa5BnqhjdS5K2whv5RN1ZMQhKZ9xsP.a2terminator2 [192.168.1.16:60696]
08/18/2017 01:05:10 +03:00 [Debug] [CoiniumServ.Shares.ShareManager] [Scorecoin] Share accepted at 10616.61/8192 by miner SbfEqa5BnqhjdS5K2whv5RN1ZMQhKZ9xsP.a2terminator2
08/18/2017 01:05:15 +03:00 [Debug] [CoiniumServ.Shares.ShareManager] [Scorecoin] Share accepted at 10213.18/8192 by miner SbfEqa5BnqhjdS5K2whv5RN1ZMQhKZ9xsP.a2terminator2
08/18/2017 01:05:19 +03:00 [Debug] [CoiniumServ.Shares.ShareManager] [Scorecoin] Share accepted at 9770.60/8192 by miner SbfEqa5BnqhjdS5K2whv5RN1ZMQhKZ9xsP.a2terminator2
08/18/2017 01:05:24 +03:00 [Debug] [CoiniumServ.Shares.ShareManager] [Scorecoin] Share accepted at 8437.39/8192 by miner SbfEqa5BnqhjdS5K2whv5RN1ZMQhKZ9xsP.a2terminator1
08/18/2017 01:05:24 +03:00 [Verbose] [CoiniumServ.Jobs.Manager.JobManager] [Litecoin] As idle job timer expired, rebroadcasting new work
08/18/2017 01:05:24 +03:00 [Information] [CoiniumServ.Jobs.Manager.JobManager] [Litecoin] Broadcasted new job 0x2 to 2 subscribers as no new blocks found for last 55 seconds
08/18/2017 01:05:24 +03:00 [Fatal] [CoiniumServ.Program] [global] Terminating because of unhandled exception!
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.Socket.DisconnectEx_Blocking(IntPtr socketHandle, IntPtr overlapped, Int32 flags, Int32 reserved)
   at System.Net.Sockets.Socket.Disconnect(Boolean reuseSocket)
   at CoiniumServ.Server.Mining.Stratum.Sockets.SocketServer.RemoveConnection(IConnection connection)
   at CoiniumServ.Server.Mining.Stratum.Sockets.SocketServer.ReceiveCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
08/18/2017 01:05:24 +03:00 [Debug] [CoiniumServ.Server.Mining.Stratum.StratumServer] [Litecoin] Stratum client disconnected: "192.168.1.15:59643"
```

**Comment by vagabondan** [comment]
@vkynchev I haven't received such errors yet, could it be the result of dot username implementation?

**Comment by vkynchev** [comment]
@vagabondan I can't replicate it anymore... like it knows that we're gonna fix it and it's hiding. Maybe it was some old dependency left(I'm copying the files through teamViewer)... After full upload it was okay. I don't think that it is from the dot username - I'm testing it from 4 days before commiting 👍

**Comment by vkynchev** [comment]
@vagabondan The problem happens when miner is connected and then disconnected before submitting share... But it does it only on Windows... Not sure about linux😕
On windows it logs `Stratum client disconnected: "192.168.1.15:59643"`, on MacOS it logs `Stratum client disconnected: "Not Connected!"`...

**Comment by vagabondan** [comment]
I think I've reproduced this. You're right:
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x0000b] in <a07d6bf484a54da2861691df910339b1>:0 
  at System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () [0x00016] in <a07d6bf484a54da2861691df910339b1>:0 
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00029] in <26aedeede9534b948c539f8734c8492d>:0 
  at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00059] in <26aedeede9534b948c539f8734c8492d>:0 
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Boolean& found) [0x00045] in <26aedeede9534b948c539f8734c8492d>:0 
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <26aedeede9534b948c539f8734c8492d>:0 
  at CoiniumServ.Mining.MinerManager.Remove (CoiniumServ.Server.Mining.Stratum.Sockets.IConnection connection) [0x0006d] in <189281631b0449f699bf4584aa08b2e8>:0 
  at CoiniumServ.Server.Mining.Stratum.StratumServer.OnClientDisconnect (System.Object sender, CoiniumServ.Server.Mining.Stratum.Sockets.ConnectionEventArgs e) [0x00029] in <189281631b0449f699bf4584aa08b2e8>:0 
  at CoiniumServ.Server.Mining.Stratum.Sockets.SocketServer.OnClientDisconnect (CoiniumServ.Server.Mining.Stratum.Sockets.ConnectionEventArgs e) [0x00010] in <189281631b0449f699bf4584aa08b2e8>:0 
  at CoiniumServ.Server.Mining.Stratum.Sockets.SocketServer.RemoveConnection (CoiniumServ.Server.Mining.Stratum.Sockets.IConnection connection) [0x00095] in <189281631b0449f699bf4584aa08b2e8>:0 
  at CoiniumServ.Server.Mining.Stratum.Sockets.SocketServer.ReceiveCallback (System.IAsyncResult result) [0x00067] in <189281631b0449f699bf4584aa08b2e8>:0 
  at System.Net.Sockets.SocketAsyncResult+<>c__DisplayClass27_0.<Complete>b__0 (System.Object _) [0x00000] in <2b0d86369d72459baed0cee98a8e578a>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <a07d6bf484a54da2861691df910339b1>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <a07d6bf484a54da2861691df910339b1>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <a07d6bf484a54da2861691df910339b1>:0

**Comment by vagabondan** [comment]
Fixed:
https://github.com/vagabondan/CoiniumServ/commit/c95848ead24fa28b324215bf43ff99eb2a230f27

Threads synchronization bug:
while one could change the list, the other could enumerate it. Lock should include both operations.

**Comment by vagabondan** [comment]
Maybe these are 2 different problems...

**Comment by vkynchev** [comment]
@vagabondan Which ones? The socket error and the thread sync?

**Comment by vkynchev** [comment]
@vagabondan Can't we just edit `Program.cs` not to terminate the app as of .NET 1.x there is no `e.IsTerminating == false` on Unhandled exceptions? (currently testing that approach)

**Comment by vagabondan** [comment]
Is catching of all exceptions suitable?

**Comment by vkynchev** [comment]
@vagabondan Well, actually now it is doing the same thing, except when it catches unhandled exception it terminates the program... I've commented out the `_logger.Fatal` and added `_logger.Debug` in Program.cs(it is in develop-vkynchev branch on my repo)

Additionaly we could terminate the app inside another fatal exception(which we know is fatal) which could be anywhere in the code...

**Comment by vagabondan** [comment]
@vkynchev Have you caught exception finally? What is it about?
I think we should catch it here:
at CoiniumServ.Server.Mining.Stratum.Sockets.SocketServer.RemoveConnection(IConnection connection):
![image](https://user-images.githubusercontent.com/2213110/29467077-c709d7ca-8447-11e7-80ea-b8efe946db26.png)

**Comment by vkynchev** [comment]
@vagabondan No, I wasn't on a computer for a while... Now I'll try to catch it from where you suggested and try to replicate it one more time.

**Comment by vagabondan** [comment]
This should help:
https://github.com/vagabondan/CoiniumServ/commit/761eb6de8836f64b49346972fe81929f0c47d9a0

**Comment by vkynchev** [comment]
Thanks! I'll try to replicate the issue again.

**Comment by vkynchev** [comment]
Success!
<img width="803" alt="screen shot 2017-08-18 at 19 22 17" src="https://user-images.githubusercontent.com/10143016/29467839-981053e2-844a-11e7-8457-39b62284c33b.png">

**Comment by vkynchev** [comment]
@vagabondan Actually, I've fixed the issue completely by calling `Shutdown` before `Close`
Will post PR shortly...
